# Generated by Django 4.2.8 on 2026-01-07 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('heure_commande', models.TimeField(auto_now_add=True)),
                ('table', models.CharField(max_length=50)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('cuisinier', models.ForeignKey(blank=True, limit_choices_to={'role__nom': 'Cuisinier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_cuisinier', to=settings.AUTH_USER_MODEL)),
                ('gerant', models.ForeignKey(blank=True, limit_choices_to={'role__nom': 'Gérant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_gerant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commande',
                'ordering': ['-date_commande', '-heure_commande'],
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ingredients', models.TextField(verbose_name='Ingrédients')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'db_table': 'plat',
            },
        ),
        migrations.CreateModel(
            name='StatutCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('CONFIRMEE', 'Confirmée')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Statut de commande',
                'verbose_name_plural': 'Statuts de commande',
                'db_table': 'statut_commande',
            },
        ),
        migrations.CreateModel(
            name='CommandePlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commandes.plat')),
            ],
            options={
                'verbose_name': 'Commande Plat',
                'verbose_name_plural': 'Commandes Plats',
                'db_table': 'commande_plat',
                'unique_together': {('commande', 'plat')},
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='plats',
            field=models.ManyToManyField(related_name='commandes', through='commandes.CommandePlat', to='commandes.plat'),
        ),
        migrations.AddField(
            model_name='commande',
            name='serveur',
            field=models.ForeignKey(limit_choices_to={'role__nom': 'Serveur'}, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_serveur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='commandes.statutcommande'),
        ),
    ]
