# Generated by Django 4.2.8 on 2026-02-10 17:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Numéro de table')),
                ('capacite', models.PositiveIntegerField(verbose_name='Capacité (nombre de places)')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVEE', 'Réservée'), ('COMMANDES_PASSEE', 'Commandes passées'), ('EN_SERVICE', 'En service'), ('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('PAYEE', 'Payée'), ('FERMEE', 'Fermée')], default='DISPONIBLE', max_length=30)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant total des commandes')),
                ('date_ouverture', models.DateTimeField(blank=True, null=True, verbose_name="Date d'ouverture")),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'table',
                'ordering': ['numero'],
            },
        ),
        migrations.RemoveField(
            model_name='commande',
            name='description',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_acceptation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_preparation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='motif_annulation',
            field=models.TextField(blank=True, verbose_name="Motif d'annulation"),
        ),
        migrations.AddField(
            model_name='commande',
            name='motif_rejet',
            field=models.TextField(blank=True, verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='commande',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations/Notes spéciales'),
        ),
        migrations.AddField(
            model_name='plat',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='plat',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Ingrédients'),
        ),
        migrations.AlterField(
            model_name='statutcommande',
            name='nom',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('CONFIRMEE', 'Confirmée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('date_generation', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('pourboire', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('AUTRE', 'Autre')], max_length=20)),
                ('gerant', models.ForeignKey(limit_choices_to={'role__nom': 'Gérant'}, on_delete=django.db.models.deletion.PROTECT, related_name='factures_gerant', to=settings.AUTH_USER_MODEL, verbose_name='Gérant ayant validé le paiement')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='commandes.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'facture',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.AlterField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='commandes.table', verbose_name='Table'),
        ),
    ]
