# Generated by Django 6.0.1 on 2026-02-23 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_table_remove_commande_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('STOCKEE', 'Stockée'), ('EN_ATTENTE_ACCEPTATION', "En attente d'acceptation"), ('EN_PREPARATION', 'En préparation'), ('EN_ATTENTE_LIVRAISON', 'En attente de livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE_ACCEPTATION', max_length=30),
        ),
        migrations.RemoveField(
            model_name='commande',
            name='gerant',
        ),
        migrations.AddField(
            model_name='facture',
            name='serveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_serveur', to=settings.AUTH_USER_MODEL, verbose_name='Serveur'),
        ),
        migrations.AddField(
            model_name='plat',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name="URL de l'image"),
        ),
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='cuisinier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_cuisinier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='serveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_serveur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='gerant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_gerant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant validé le paiement'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_order', 'Nouvelle commande'), ('order_ready', 'Commande prête'), ('order_accepted', 'Commande acceptée'), ('order_rejected', 'Commande refusée'), ('order_cancelled', 'Commande annulée'), ('order_delivered', 'Commande livrée'), ('stock_alert', 'Alerte stock'), ('peremption_alert', 'Alerte péremption'), ('mvt_validated', 'Mouvement validé'), ('mvt_rejected', 'Mouvement rejeté')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='StatutCommande',
        ),
    ]
