# Generated by Django 4.2.8 on 2026-03-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_alter_commande_statut_remove_commande_gerant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='items_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='Snapshot des articles facturés'),
        ),
    ]
