# Generated by Django 4.2.8 on 2026-03-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_facture_items_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='commandes.commande', verbose_name='Commande'),
        ),
    ]
