# Generated by Django 4.2.8 on 2026-03-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_commande_is_paid_facture_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('STOCKEE', 'Stockée'), ('EN_ATTENTE_ACCEPTATION', "En attente d'acceptation"), ('EN_PREPARATION', 'En préparation'), ('EN_ATTENTE_LIVRAISON', 'En attente de livraison'), ('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE_ACCEPTATION', max_length=30),
        ),
    ]
