# Generated by Django 4.2.8 on 2026-03-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_order', 'Nouvelle commande'), ('order_ready', 'Commande prête'), ('order_accepted', 'Commande acceptée'), ('order_rejected', 'Commande refusée'), ('order_cancelled', 'Commande annulée'), ('order_delivered', 'Commande livrée'), ('stock_alert', 'Alerte stock'), ('peremption_alert', 'Alerte péremption'), ('mvt_validated', 'Mouvement validé'), ('mvt_rejected', 'Mouvement rejeté'), ('demande_stock', 'Demande de stock'), ('demande_validee', 'Demande validée'), ('demande_rejetee', 'Demande rejetée'), ('table_closed', 'Table clôturée'), ('order_delivered', 'Commande livrée')], max_length=30),
        ),
    ]
