# Generated by Django 4.2.8 on 2026-04-10 11:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
        ('commandes', '0009_alter_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande', '-heure_commande'], 'verbose_name': 'Commande'},
        ),
        migrations.AlterModelOptions(
            name='commandeplat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'verbose_name': 'Facture'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='plat',
            options={'verbose_name': 'Plat'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['numero'], 'verbose_name': 'Table'},
        ),
        migrations.AlterUniqueTogether(
            name='commandeplat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='facture',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='gerant',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='items_snapshot',
        ),
        migrations.AddField(
            model_name='commande',
            name='nom_client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='source',
            field=models.CharField(choices=[('serveur', 'Serveur'), ('client_qr', 'Client (QR Code)')], default='serveur', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='commandes',
            field=models.ManyToManyField(blank=True, to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plat',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='table',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='motif_annulation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='motif_rejet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='serveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_serveur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='commandes.table'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_generation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='serveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='commandes.table'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_order', 'Nouvelle commande'), ('order_accepted', 'Commande acceptée'), ('order_rejected', 'Commande refusée'), ('order_ready', 'Commande prête'), ('order_delivered', 'Commande livrée'), ('order_cancelled', 'Commande annulée'), ('stock_alert', 'Alerte stock'), ('peremption_alert', 'Alerte péremption'), ('mvt_validated', 'Mouvement validé'), ('mvt_rejected', 'Mouvement rejeté'), ('demande_stock', 'Demande de stock'), ('demande_validee', 'Demande validée'), ('demande_rejetee', 'Demande rejetée')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plat',
            name='categorie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plat',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='date_ouverture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='table',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Numéro de table'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'numero')},
        ),
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
