# Generated by Django 4.2.8 on 2026-01-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Migration vide - voir 0003_create_roles_and_admin pour la création des données
    ]
