# Generated by Django 4.2.8 on 2026-02-10

from django.db import migrations
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
import os




class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_superuser'),
    ]

    operations = [
        # migrations.RunPython(create_roles_and_superuser, reverse_create_roles)
    ]
