# Generated by Django 4.2.8 on 2026-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_roles_and_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
    ]
