# Generated by Django 4.2.8 on 2026-02-24 09:04

import os

from django.db import migrations
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password

class Migration(migrations.Migration):

    def create_roles_and_superuser(app, schema_editor):
        """Crée les rôles et l'utilisateur admin"""
        from users.models import Role
        
        User = get_user_model()
        
        # Créer les rôles s'ils n'existent pas
        roles = [
            ('Serveur', 'Serveur du restaurant'),
            ('Cuisinier', 'Cuisinier'),
            ('Gérant', 'Gérant du restaurant'),
            ('Gestionnaire de stock', 'Responsable de la gestion des stocks'),
            ('Manager', 'Manager'),
            ('Auditeur', 'Auditeur'),
            ('Administrateur', 'Administrateur du système'),
        ]
        
        role_admin = None
        for role_nom, role_desc in roles:
            role, created = Role.objects.get_or_create(
                nom=role_nom,
                defaults={'description': role_desc}
            )
            if role_nom == 'Administrateur':
                role_admin = role
        
        # Créer le superutilisateur s'il n'existe pas
        login = os.environ.get('ADMIN_USERNAME', 'admin1')
        if not User.objects.filter(login=login).exists():
            User.objects.create(
                login=login,
                email=os.environ.get('ADMIN_EMAIL', 'admin@restaurant.com'),
                password=make_password(os.environ.get('ADMIN_PASSWORD', 'password123')),
                first_name=os.environ.get('ADMIN_FIRSTNAME', 'Admin'),
                last_name=os.environ.get('ADMIN_LASTNAME', 'System'),
                date_de_naissance='1990-05-15',
                sexe='M',
                date_embauche='2024-01-10',
                role=role_admin,
                # is_superuser=True,
                is_staff=True,
                is_activite=True
            )


    def reverse_create_roles(app, schema_editor):
        """Annuler la création - on peut laisser les données"""
        pass

    dependencies = [
        ('users', '0007_alter_permission_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_roles_and_superuser, reverse_create_roles)
    ]
