# Generated by Django 4.2.8 on 2026-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20260224_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
    ]
