# Generated by Django 4.2.8 on 2026-04-11 08:56

import os

from django.db import migrations
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_date_de_naissance'),
    ]
    
    def create_roles_and_superuser(app, schema_editor):
        """Crée l'utilisateur admin"""
        from users.models import Role
        
        User = get_user_model()
        
        role_admin = Role.objects.get(nom='Administrateur')
        # Créer le superutilisateur s'il n'existe pas
        login = os.environ.get('ADMIN_USERNAME', 'superadmin1')
        if not User.objects.filter(login=login).exists():
            User.objects.create(
                login=login,
                email=os.environ.get('ADMIN_EMAIL', 'superadmin@restaurant.com'),
                password=make_password(os.environ.get('ADMIN_PASSWORD', 'password123')),
                first_name=os.environ.get('ADMIN_FIRSTNAME', 'Admin'),
                last_name=os.environ.get('ADMIN_LASTNAME', 'System'),
                date_de_naissance='1990-05-15',
                sexe='M',
                date_embauche='2024-01-10',
                role=role_admin,
                is_super_admin=True,
                is_staff=True,
                is_activite=True
            )


    def reverse_create_roles(app, schema_editor):
        """Annuler la création - on peut laisser les données"""
        pass

    operations = [
        migrations.RunPython(create_roles_and_superuser, reverse_code=reverse_create_roles),
    ]
