# Generated by Django 4.2.8 on 2026-04-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20260411_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
