# Generated by Django 4.2.8 on 2026-04-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_update_plan_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('essai', 'Essai'), ('expiré', 'Expiré'), ('annulé', 'Annulé')], default='essai', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='module_commandes',
            field=models.BooleanField(default=True, help_text='Module commandes, tables, facturation'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='module_stock',
            field=models.BooleanField(default=False, help_text='Module gestion des stocks'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL publique du logo du restaurant'),
        ),
    ]
