# Generated by Django 4.2.8 on 2026-01-07 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Seuil minimum')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'produit',
            },
        ),
        migrations.CreateModel(
            name='StatutDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Statut de demande',
                'verbose_name_plural': 'Statuts de demande',
                'db_table': 'statut_demande',
            },
        ),
        migrations.CreateModel(
            name='StatutMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Statut de mouvement',
                'verbose_name_plural': 'Statuts de mouvement',
                'db_table': 'statut_mouvement',
            },
        ),
        migrations.CreateModel(
            name='TypeMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('SUPPRESSION', 'Suppression')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Type de mouvement',
                'verbose_name_plural': 'Types de mouvement',
                'db_table': 'type_mouvement',
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'db_table': 'unite',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_dispo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité disponible')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='stocks.produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='stocks.unite'),
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('justification', models.TextField(blank=True, verbose_name='Justification/Motif')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_demandes', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stocks.produit')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stocks.statutmouvement')),
                ('type_mouvement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stocks.typemouvement')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_valides', to=settings.AUTH_USER_MODEL, verbose_name='Valideur')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'mouvement_stock',
                'ordering': ['-date', '-heure'],
            },
        ),
        migrations.CreateModel(
            name='DemandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(verbose_name='Justification')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_produits', to='commandes.commande', verbose_name='Commande liée')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_produits', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur (Cuisinier)')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='stocks.produit')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Valideur (Gérant)')),
            ],
            options={
                'verbose_name': 'Demande de produit',
                'verbose_name_plural': 'Demandes de produit',
                'db_table': 'demande_produit',
                'ordering': ['-date_demande'],
            },
        ),
    ]
