# Generated by Django 4.2.8 on 2026-02-10 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeproduit',
            name='motif_rejet',
            field=models.TextField(blank=True, verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='date_reception',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception (pour les entrées)'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fournisseur (pour les entrées)'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='motif_rejet',
            field=models.TextField(blank=True, verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_peremption',
            field=models.DateField(blank=True, null=True, verbose_name='Date de péremption'),
        ),
        migrations.AlterField(
            model_name='demandeproduit',
            name='valideur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Valideur (Gérant ou Gestionnaire de stock)'),
        ),
    ]
