# Generated by Django 4.2.8 on 2026-03-06 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_demandeproduit_motif_rejet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='date_reception',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réception (pour les entrées)'),
        ),
    ]
