# Generated by Django 4.2.8 on 2026-01-07 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('PDF', 'PDF')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': "Format d'export",
                'verbose_name_plural': "Formats d'export",
                'db_table': 'format_export',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMMANDES', 'Commandes'), ('STOCKS', 'Stocks'), ('UTILISATEURS', 'Utilisateurs'), ('AUDIT', 'Audit'), ('KPI', 'KPI')], max_length=50)),
                ('periode', models.CharField(max_length=100, verbose_name='Période')),
                ('contenu', models.TextField()),
                ('date_generation', models.DateTimeField(default=django.utils.timezone.now)),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'rapport',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='LogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('VALIDATE', 'Validation'), ('REJECT', 'Rejet'), ('APPROVE', 'Approbation'), ('CANCEL', 'Annulation')], max_length=20)),
                ('type_action', models.CharField(max_length=100, verbose_name="Type d'action")),
                ('date_action', models.DateField(default=django.utils.timezone.now)),
                ('heure_action', models.TimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('table_name', models.CharField(blank=True, max_length=100, verbose_name='Table concernée')),
                ('record_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'enregistrement")),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'db_table': 'log_audit',
                'ordering': ['-date_action', '-heure_action'],
                'indexes': [models.Index(fields=['user', 'date_action'], name='log_audit_user_id_f93e90_idx'), models.Index(fields=['action', 'date_action'], name='log_audit_action_9b4db3_idx'), models.Index(fields=['table_name', 'record_id'], name='log_audit_table_n_f227ef_idx')],
            },
        ),
    ]
